"""initial schema

Revision ID: 7930dbac353a
Revises: 
Create Date: 2026-10-01 16:18:44.077995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7930dbac353a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configurations")),
    )
    op.create_index(op.f("ix_configurations_key"), "configurations", ["key"], unique=True)
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "practice_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["practice_categories.id"],
            name=op.f("fk_practice_categories_parent_id_practice_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_practice_categories_slug")),
    )
    op.create_table(
        "practice_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_practice_tags_slug")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_table(
        "practices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("objectives", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="practice_difficulty"),
            nullable=False,
        ),
        sa.Column("estimated_time_minutes", sa.Integer(), nullable=False),
        sa.Column("technologies", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "embedding_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="practice_status"),
            nullable=False,
        ),
        sa.Column("practice_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["practice_categories.id"],
            name=op.f("fk_practices_category_id_practice_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_practices_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practices")),
    )
    op.create_index(op.f("ix_practices_slug"), "practices", ["slug"], unique=True)
    op.create_index(op.f("ix_practices_type"), "practices", ["type"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "ai_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=True),
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "ERROR", "STOPPED", name="ai_session_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("iterations_used", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("session_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_ai_sessions_practice_id_practices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_sessions")),
    )
    op.create_index(op.f("ix_ai_sessions_user_id"), "ai_sessions", ["user_id"], unique=False)
    op.create_table(
        "practice_contents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_practice_contents_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_practice_contents_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_contents")),
    )
    op.create_table(
        "practice_practice_tags",
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_practice_practice_tags_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["practice_tags.id"],
            name=op.f("fk_practice_practice_tags_tag_id_practice_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("practice_id", "tag_id", name=op.f("pk_practice_practice_tags")),
    )
    op.create_table(
        "student_practice_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "SUBMITTED", "EVALUATED", "ABANDONED", name="attempt_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_student_practice_attempts_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_student_practice_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_practice_attempts")),
    )
    op.create_index(
        op.f("ix_student_practice_attempts_practice_id"),
        "student_practice_attempts",
        ["practice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_practice_attempts_user_id"),
        "student_practice_attempts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "student_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "COMPLETED", name="progress_status"),
            nullable=False,
        ),
        sa.Column("best_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("attempts_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_student_progress_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_student_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_progress")),
        sa.UniqueConstraint("user_id", "practice_id", name="uq_student_progress_user_practice"),
    )
    op.create_index(
        op.f("ix_student_progress_practice_id"), "student_progress", ["practice_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_progress_user_id"), "student_progress", ["user_id"], unique=False
    )
    op.create_table(
        "ai_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", "SYSTEM", "TOOL", name="ai_message_role"),
            nullable=False,
        ),
        sa.Column("content", sa.String(length=8000), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["ai_sessions.id"],
            name=op.f("fk_ai_messages_session_id_ai_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_messages")),
    )
    op.create_index(op.f("ix_ai_messages_session_id"), "ai_messages", ["session_id"], unique=False)
    op.create_table(
        "ai_tool_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("iteration_index", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "ERROR", "DENIED", name="ai_tool_call_status"),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["ai_sessions.id"],
            name=op.f("fk_ai_tool_calls_session_id_ai_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_tool_calls")),
    )
    op.create_index(
        op.f("ix_ai_tool_calls_session_id"), "ai_tool_calls", ["session_id"], unique=False
    )
    op.create_table(
        "practice_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("practice_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["student_practice_attempts.id"],
            name=op.f("fk_practice_submissions_attempt_id_student_practice_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
            name=op.f("fk_practice_submissions_practice_id_practices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_practice_submissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_submissions")),
    )
    op.create_index(
        op.f("ix_practice_submissions_attempt_id"),
        "practice_submissions",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "practice_evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("feedback", sa.String(length=2000), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "evaluated_by", sa.Enum("AI", "HUMAN", "SYSTEM", name="evaluator_type"), nullable=False
        ),
        sa.Column("evaluator_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluator_user_id"],
            ["users.id"],
            name=op.f("fk_practice_evaluations_evaluator_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["practice_submissions.id"],
            name=op.f("fk_practice_evaluations_submission_id_practice_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_evaluations")),
    )
    op.create_index(
        op.f("ix_practice_evaluations_submission_id"),
        "practice_evaluations",
        ["submission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_practice_evaluations_submission_id"), table_name="practice_evaluations")
    op.drop_table("practice_evaluations")
    op.drop_index(op.f("ix_practice_submissions_attempt_id"), table_name="practice_submissions")
    op.drop_table("practice_submissions")
    op.drop_index(op.f("ix_ai_tool_calls_session_id"), table_name="ai_tool_calls")
    op.drop_table("ai_tool_calls")
    op.drop_index(op.f("ix_ai_messages_session_id"), table_name="ai_messages")
    op.drop_table("ai_messages")
    op.drop_index(op.f("ix_student_progress_user_id"), table_name="student_progress")
    op.drop_index(op.f("ix_student_progress_practice_id"), table_name="student_progress")
    op.drop_table("student_progress")
    op.drop_index(
        op.f("ix_student_practice_attempts_user_id"), table_name="student_practice_attempts"
    )
    op.drop_index(
        op.f("ix_student_practice_attempts_practice_id"), table_name="student_practice_attempts"
    )
    op.drop_table("student_practice_attempts")
    op.drop_table("practice_practice_tags")
    op.drop_table("practice_contents")
    op.drop_index(op.f("ix_ai_sessions_user_id"), table_name="ai_sessions")
    op.drop_table("ai_sessions")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_practices_type"), table_name="practices")
    op.drop_index(op.f("ix_practices_slug"), table_name="practices")
    op.drop_table("practices")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("practice_tags")
    op.drop_table("practice_categories")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_configurations_key"), table_name="configurations")
    op.drop_table("configurations")
    # ### end Alembic commands ###
    # Postgres no elimina los tipos ENUM al hacer drop de las tablas que los usan;
    # se eliminan explicitamente para que upgrade() sea repetible tras un downgrade.
    bind = op.get_bind()
    for enum_name in (
        "practice_difficulty",
        "practice_status",
        "ai_session_status",
        "attempt_status",
        "progress_status",
        "ai_message_role",
        "ai_tool_call_status",
        "evaluator_type",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
