"""Traducciones (en/pt/fr) del contenido pedagogico de las 4 practicas iniciales (ver
practices_data.py, fuente de verdad en espanol). Cada entrada es un overlay parcial:
solo lleva las claves de `content` que son texto dirigido a quien usa la practica
(etiquetas, reglas redactadas en prosa, preguntas); los valores numericos, unidades,
identificadores de practica y discriminadores de tipo no se repiten aqui porque no
cambian entre idiomas (ver app.domain.services.practice_localization para el merge).

Mantener en sincronia con practices_data.py: un campo nuevo agregado alli en espanol
sigue sin traduccion hasta que se agregue aqui (fallback automatico al espanol, nunca
un error)."""

from typing import Any

PRACTICE_TRANSLATIONS: dict[str, dict[str, Any]] = {
    "software-01-simulacion-mru": {
        "en": {
            "title": "Uniform rectilinear motion simulation",
            "description": (
                "Build, step by step and with AI assistance, a browser activity where "
                "the student predicts the distance traveled at constant speed, adjusts "
                "speed and time, and compares their prediction with the calculated "
                "result."
            ),
            "objectives": [
                "Build, with AI assistance, an interactive prediction-and-verification activity",
                "Express an explicit physical model (distance = speed × time) in code, not in text generated by the language model",
                "Apply the sequence predict → adjust → execute → observe → explain",
            ],
            "instructions": (
                "Build the activity in five steps. (1) Write down the goal and the "
                "assumptions: travel at constant speed, distance = speed × time, speed "
                "between 0 and 100 km/h, time between 0 and 3 hours; acceleration, "
                "traffic, and stops are outside the model. (2) Implement the fixed "
                "sequence predict → adjust → execute → observe → explain: you cannot "
                "adjust without having predicted first. (3) Build the controls (sliders "
                "or fields with visible units, keyboard-accessible, with a reset "
                "button) and calculate the distance in code, never estimated by the "
                "language model. (4) Show the numeric result with its text equivalent "
                "and feedback that compares the student's prediction with the "
                "calculated result. (5) Verify the three numeric examples and answer "
                "the transfer question with new values."
            ),
            "content": {
                "model": {
                    "variables": {
                        "speed_kmh": {"label": "Speed"},
                        "time_h": {"label": "Time"},
                    },
                    "assumptions": ["constant speed", "no acceleration, traffic, or stops"],
                },
                "transfer_question": "How much time is needed at 80 km/h to travel 200 km?",
                "reflection_questions": [
                    "What relationship do you observe between time and distance when speed is constant?",
                    "What would happen to the visual representation if the speed doubled?",
                ],
            },
        },
        "pt": {
            "title": "Simulação de movimento retilíneo uniforme",
            "description": (
                "Construa, passo a passo e com ajuda de IA, uma atividade de navegador "
                "em que o estudante prevê a distância percorrida a velocidade "
                "constante, ajusta velocidade e tempo, e compara sua predição com o "
                "resultado calculado."
            ),
            "objectives": [
                "Construir, com apoio de IA, uma atividade interativa de predição e verificação",
                "Expressar um modelo físico explícito (distância = velocidade × tempo) em código, não em texto gerado pelo modelo de linguagem",
                "Aplicar a sequência prever → ajustar → executar → observar → explicar",
            ],
            "instructions": (
                "Construa a atividade em cinco passos. (1) Escreva o objetivo e as "
                "suposições: viagem a velocidade constante, distância = velocidade × "
                "tempo, velocidade entre 0 e 100 km/h, tempo entre 0 e 3 horas; "
                "aceleração, trânsito e paradas ficam fora do modelo. (2) Implemente a "
                "sequência fixa prever → ajustar → executar → observar → explicar: não "
                "é possível ajustar sem antes ter previsto. (3) Construa os controles "
                "(controles deslizantes ou campos com unidades visíveis, acessíveis "
                "por teclado, com botão de reinício) e calcule a distância em código, "
                "nunca estimada pelo modelo de linguagem. (4) Mostre o resultado "
                "numérico com seu equivalente textual e uma retroalimentação que "
                "compare a predição do estudante com o resultado calculado. (5) "
                "Verifique os três exemplos numéricos e responda à pergunta de "
                "transferência com valores novos."
            ),
            "content": {
                "model": {
                    "variables": {
                        "speed_kmh": {"label": "Velocidade"},
                        "time_h": {"label": "Tempo"},
                    },
                    "assumptions": ["velocidade constante", "sem aceleração, trânsito ou paradas"],
                },
                "transfer_question": "Quanto tempo é necessário a 80 km/h para percorrer 200 km?",
                "reflection_questions": [
                    "Que relação você observa entre o tempo e a distância quando a velocidade é constante?",
                    "O que aconteceria com a representação visual se a velocidade dobrasse?",
                ],
            },
        },
        "fr": {
            "title": "Simulation de mouvement rectiligne uniforme",
            "description": (
                "Construisez, étape par étape et avec l'aide de l'IA, une activité de "
                "navigateur où l'étudiant prédit la distance parcourue à vitesse "
                "constante, ajuste la vitesse et le temps, et compare sa prédiction "
                "avec le résultat calculé."
            ),
            "objectives": [
                "Construire, avec l'aide de l'IA, une activité interactive de prédiction et de vérification",
                "Exprimer un modèle physique explicite (distance = vitesse × temps) en code, et non dans un texte généré par le modèle de langage",
                "Appliquer la séquence prédire → ajuster → exécuter → observer → expliquer",
            ],
            "instructions": (
                "Construisez l'activité en cinq étapes. (1) Écrivez l'objectif et les "
                "hypothèses : trajet à vitesse constante, distance = vitesse × temps, "
                "vitesse entre 0 et 100 km/h, temps entre 0 et 3 heures ; "
                "l'accélération, la circulation et les arrêts restent hors du modèle. "
                "(2) Implémentez la séquence fixe prédire → ajuster → exécuter → "
                "observer → expliquer : impossible d'ajuster sans avoir prédit "
                "d'abord. (3) Construisez les contrôles (curseurs ou champs avec "
                "unités visibles, accessibles au clavier, avec un bouton de "
                "réinitialisation) et calculez la distance dans le code, jamais "
                "estimée par le modèle de langage. (4) Affichez le résultat numérique "
                "avec son équivalent textuel et une rétroaction qui compare la "
                "prédiction de l'étudiant avec le résultat calculé. (5) Vérifiez les "
                "trois exemples numériques et répondez à la question de transfert "
                "avec de nouvelles valeurs."
            ),
            "content": {
                "model": {
                    "variables": {
                        "speed_kmh": {"label": "Vitesse"},
                        "time_h": {"label": "Temps"},
                    },
                    "assumptions": ["vitesse constante", "sans accélération, circulation ni arrêts"],
                },
                "transfer_question": "Combien de temps faut-il à 80 km/h pour parcourir 200 km ?",
                "reflection_questions": [
                    "Quelle relation observez-vous entre le temps et la distance lorsque la vitesse est constante ?",
                    "Que se passerait-il pour la représentation visuelle si la vitesse doublait ?",
                ],
            },
        },
    },
    "software-02-depuracion-mru": {
        "en": {
            "title": "Debugging an AI-generated simulation",
            "description": (
                "Starting from a version with intentional bugs of the MRU simulation "
                "(practice software-01), identify and fix the faults using its "
                "acceptance criteria as the reference for correctness."
            ),
            "objectives": [
                "Analyze AI-generated code against a written specification",
                "Detect and fix boundary-validation and accessibility errors",
                "Use the base practice's acceptance criteria as regression tests",
            ],
            "instructions": (
                "You are given a version of the MRU simulation with three intentional "
                "bugs (see `content.buggy_version_description`). Ask an AI assistant "
                "for help locating them, but verify each fix yourself against the "
                "acceptance criteria in `content.acceptance_criteria`: a change that "
                "'seems to work' is not enough if it doesn't pass all four cases. "
                "Submit the corrected code and a brief note on what caused each bug."
            ),
            "content": {
                "buggy_version_description": {
                    "bug_1": "The form accepts negative speeds and uses them in the calculation without showing an error.",
                    "bug_2": "When time = 0, the code shows 'NaN km' instead of 0 km.",
                    "bug_3": "The speed and time controls only respond to the mouse; they cannot be operated with the keyboard.",
                },
                "acceptance_criteria": [
                    "40 km/h for 1.5 hours must produce 60 km",
                    "Time 0 must produce distance 0",
                    "A negative value must produce a clear error, not a result",
                    "The activity must be completable using only the keyboard",
                ],
            },
        },
        "pt": {
            "title": "Depuração de uma simulação gerada por IA",
            "description": (
                "A partir de uma versão com erros intencionais da simulação de MRU "
                "(prática software-01), identifique e corrija as falhas usando seus "
                "critérios de aceitação como referência de correção."
            ),
            "objectives": [
                "Analisar código gerado por IA em relação a uma especificação escrita",
                "Detectar e corrigir erros de validação de limites e de acessibilidade",
                "Usar os critérios de aceitação da prática base como testes de regressão",
            ],
            "instructions": (
                "Você recebe uma versão da simulação de MRU com três falhas "
                "intencionais (veja `content.buggy_version_description`). Peça ajuda a "
                "um assistente de IA para localizá-las, mas verifique cada correção "
                "você mesmo em relação aos critérios de aceitação de "
                "`content.acceptance_criteria`: uma mudança que 'parece funcionar' não "
                "é suficiente se não passar nos quatro casos. Entregue o código "
                "corrigido e uma nota breve sobre o que causava cada falha."
            ),
            "content": {
                "buggy_version_description": {
                    "bug_1": "O formulário aceita velocidades negativas e as usa no cálculo sem mostrar erro.",
                    "bug_2": "Quando tempo = 0, o código mostra 'NaN km' em vez de 0 km.",
                    "bug_3": "Os controles de velocidade e tempo só respondem ao mouse; não são operáveis pelo teclado.",
                },
                "acceptance_criteria": [
                    "40 km/h durante 1,5 horas devem produzir 60 km",
                    "Tempo 0 deve produzir distância 0",
                    "Um valor negativo deve gerar um erro claro, não um resultado",
                    "A atividade deve poder ser concluída apenas com o teclado",
                ],
            },
        },
        "fr": {
            "title": "Débogage d'une simulation générée par IA",
            "description": (
                "À partir d'une version avec des bugs intentionnels de la simulation "
                "de MRU (pratique software-01), identifiez et corrigez les défauts en "
                "utilisant ses critères d'acceptation comme référence de correction."
            ),
            "objectives": [
                "Analyser du code généré par IA par rapport à une spécification écrite",
                "Détecter et corriger des erreurs de validation des limites et d'accessibilité",
                "Utiliser les critères d'acceptation de la pratique de base comme tests de régression",
            ],
            "instructions": (
                "On vous donne une version de la simulation de MRU avec trois bugs "
                "intentionnels (voir `content.buggy_version_description`). Demandez "
                "l'aide d'un assistant IA pour les localiser, mais vérifiez vous-même "
                "chaque correction par rapport aux critères d'acceptation de "
                "`content.acceptance_criteria` : un changement qui « semble "
                "fonctionner » ne suffit pas s'il ne passe pas les quatre cas. "
                "Soumettez le code corrigé et une brève note sur la cause de chaque "
                "bug."
            ),
            "content": {
                "buggy_version_description": {
                    "bug_1": "Le formulaire accepte des vitesses négatives et les utilise dans le calcul sans afficher d'erreur.",
                    "bug_2": "Quand temps = 0, le code affiche « NaN km » au lieu de 0 km.",
                    "bug_3": "Les contrôles de vitesse et de temps ne répondent qu'à la souris ; ils ne peuvent pas être utilisés au clavier.",
                },
                "acceptance_criteria": [
                    "40 km/h pendant 1,5 heure doit produire 60 km",
                    "Un temps de 0 doit produire une distance de 0",
                    "Une valeur négative doit produire une erreur claire, pas un résultat",
                    "L'activité doit pouvoir être réalisée entièrement au clavier",
                ],
            },
        },
    },
    "image-01-conteo-circulos": {
        "en": {
            "title": "Prototype for counting paper circles",
            "description": (
                "Build a prototype that counts colored paper circles in images using "
                "an explicit rule, showing the proposed count and a visible warning "
                "for illegible images."
            ),
            "objectives": [
                "Build an object-counting prototype with an explicit rule",
                "Compare the proposed count against a human reference",
                "Recognize the limits of what a model can infer from an image",
            ],
            "instructions": (
                "Build the prototype in five steps. (1) Write the counting rule with "
                "its four parts: what counts (a circle whose center is visible), what "
                "does not count (no visible center, reflections, shadows), when an "
                "image is illegible (blur that prevents the centers from being seen), "
                "and what is always preserved (identifier, method version, per-image "
                "result). (2) Prepare a human reference with at least two independent "
                "labelers; reconcile disagreements before testing. (3) Split the "
                "images into 12 development images and 8 reserved for testing; "
                "near-identical photographs stay in the same group. (4) Build the "
                "viewer (image, proposed count, confidence, warning, method version) "
                "and test it with the 12 development images. (5) Run the final method "
                "exactly once on the 8 reserved images and write the error report."
            ),
            "content": {
                "counting_rule": {
                    "counts": "a circle whose center is visible",
                    "excludes": ["circles without a visible center", "reflections", "shadows"],
                    "illegible_when": ["blur that prevents the centers from being seen"],
                    "always_preserved": [
                        "image identifier",
                        "method version",
                        "per-image result",
                    ],
                },
            },
        },
        "pt": {
            "title": "Protótipo de contagem de círculos de papel",
            "description": (
                "Construa um protótipo que conte círculos de papel coloridos em "
                "imagens com uma regra explícita, mostrando a contagem proposta e um "
                "aviso visível diante de imagens ilegíveis."
            ),
            "objectives": [
                "Construir um protótipo de contagem de objetos com uma regra explícita",
                "Comparar a contagem proposta com uma referência humana",
                "Reconhecer os limites do que um modelo pode inferir de uma imagem",
            ],
            "instructions": (
                "Construa o protótipo em cinco passos. (1) Escreva a regra de "
                "contagem com suas quatro partes: o que conta (um círculo cujo centro "
                "é visível), o que não conta (sem centro visível, reflexos, sombras), "
                "quando a imagem é ilegível (desfoque que impede ver os centros) e o "
                "que se conserva sempre (identificador, versão do método, resultado "
                "por imagem). (2) Prepare uma referência humana com pelo menos dois "
                "rotuladores independentes; concilie as divergências antes de testar. "
                "(3) Divida as imagens em 12 de desenvolvimento e 8 reservadas para o "
                "teste; fotografias quase idênticas permanecem no mesmo grupo. (4) "
                "Construa o visualizador (imagem, contagem proposta, confiança, aviso, "
                "versão do método) e teste-o com as 12 imagens de desenvolvimento. (5) "
                "Execute o método definitivo uma única vez sobre as 8 imagens "
                "reservadas e redija o relatório de erros."
            ),
            "content": {
                "counting_rule": {
                    "counts": "um círculo cujo centro é visível",
                    "excludes": ["círculos sem centro visível", "reflexos", "sombras"],
                    "illegible_when": ["desfoque que impede ver os centros"],
                    "always_preserved": [
                        "identificador da imagem",
                        "versão do método",
                        "resultado por imagem",
                    ],
                },
            },
        },
        "fr": {
            "title": "Prototype de comptage de cercles en papier",
            "description": (
                "Construisez un prototype qui compte des cercles en papier colorés "
                "dans des images à l'aide d'une règle explicite, en affichant le "
                "comptage proposé et un avertissement visible pour les images "
                "illisibles."
            ),
            "objectives": [
                "Construire un prototype de comptage d'objets avec une règle explicite",
                "Comparer le comptage proposé à une référence humaine",
                "Reconnaître les limites de ce qu'un modèle peut déduire d'une image",
            ],
            "instructions": (
                "Construisez le prototype en cinq étapes. (1) Écrivez la règle de "
                "comptage avec ses quatre parties : ce qui compte (un cercle dont le "
                "centre est visible), ce qui ne compte pas (centre non visible, "
                "reflets, ombres), quand une image est illisible (flou empêchant de "
                "voir les centres), et ce qui est toujours conservé (identifiant, "
                "version de la méthode, résultat par image). (2) Préparez une "
                "référence humaine avec au moins deux annotateurs indépendants ; "
                "réconciliez les désaccords avant de tester. (3) Répartissez les "
                "images en 12 images de développement et 8 réservées pour le test ; "
                "les photographies quasi identiques restent dans le même groupe. (4) "
                "Construisez le visualiseur (image, comptage proposé, confiance, "
                "avertissement, version de la méthode) et testez-le avec les 12 "
                "images de développement. (5) Exécutez la méthode finale exactement "
                "une fois sur les 8 images réservées et rédigez le rapport d'erreurs."
            ),
            "content": {
                "counting_rule": {
                    "counts": "un cercle dont le centre est visible",
                    "excludes": ["cercles sans centre visible", "reflets", "ombres"],
                    "illegible_when": ["flou empêchant de voir les centres"],
                    "always_preserved": [
                        "identifiant de l'image",
                        "version de la méthode",
                        "résultat par image",
                    ],
                },
            },
        },
    },
    "image-02-diagnostico-errores": {
        "en": {
            "title": "Diagnosing counting errors",
            "description": (
                "Using the results of 'Prototype for counting paper circles' "
                "(image-01), classify the errors of the 8 reserved images by "
                "difficult condition and propose an adjustment to the counting rule."
            ),
            "objectives": [
                "Interpret error patterns of a counting method (lighting, overlap, blur)",
                "Propose an adjustment to the counting rule based on evidence",
            ],
            "instructions": (
                "Start from the error report from step 5 of practice image-01: "
                "compare each proposed count with the human reference on the 8 "
                "reserved images. Classify each error by condition (lighting, "
                "overlap, or blur), note at least two errors with an explanation of "
                "their probable cause, and propose a concrete adjustment to the "
                "counting rule (without yet running the reserved test again: changing "
                "the rule invalidates that test and requires a new reserved set)."
            ),
            "content": {
                "required_output": [
                    "error table by condition",
                    "at least two annotated errors with an explanation",
                    "a proposed adjustment to the rule",
                ],
            },
        },
        "pt": {
            "title": "Diagnóstico de erros de contagem",
            "description": (
                "Usando os resultados de 'Protótipo de contagem de círculos de papel' "
                "(image-01), classifique os erros das 8 imagens reservadas por "
                "condição difícil e proponha um ajuste à regra de contagem."
            ),
            "objectives": [
                "Interpretar padrões de erro de um método de contagem (iluminação, sobreposição, desfoque)",
                "Propor um ajuste à regra de contagem a partir de evidências",
            ],
            "instructions": (
                "Parta do relatório de erros do passo 5 da prática image-01: compare "
                "cada contagem proposta com a referência humana nas 8 imagens "
                "reservadas. Classifique cada erro por condição (iluminação, "
                "sobreposição ou desfoque), anote pelo menos dois erros com uma "
                "explicação de sua causa provável, e proponha um ajuste concreto à "
                "regra de contagem (sem ainda executar novamente o teste reservado: "
                "mudar a regra invalida esse teste e exige um novo conjunto "
                "reservado)."
            ),
            "content": {
                "required_output": [
                    "tabela de erro por condição",
                    "pelo menos dois erros anotados com explicação",
                    "uma proposta de ajuste à regra",
                ],
            },
        },
        "fr": {
            "title": "Diagnostic des erreurs de comptage",
            "description": (
                "À partir des résultats de « Prototype de comptage de cercles en "
                "papier » (image-01), classez les erreurs des 8 images réservées par "
                "condition difficile et proposez un ajustement de la règle de "
                "comptage."
            ),
            "objectives": [
                "Interpréter les schémas d'erreur d'une méthode de comptage (éclairage, chevauchement, flou)",
                "Proposer un ajustement de la règle de comptage fondé sur des preuves",
            ],
            "instructions": (
                "Partez du rapport d'erreurs de l'étape 5 de la pratique image-01 : "
                "comparez chaque comptage proposé à la référence humaine sur les 8 "
                "images réservées. Classez chaque erreur par condition (éclairage, "
                "chevauchement ou flou), notez au moins deux erreurs avec une "
                "explication de leur cause probable, et proposez un ajustement "
                "concret de la règle de comptage (sans encore relancer le test "
                "réservé : modifier la règle invalide ce test et exige un nouvel "
                "ensemble réservé)."
            ),
            "content": {
                "required_output": [
                    "tableau d'erreurs par condition",
                    "au moins deux erreurs annotées avec explication",
                    "une proposition d'ajustement de la règle",
                ],
            },
        },
    },
}
