import uuid
from typing import Protocol

from app.domain.entities.identity import PasswordResetToken, Permission, Role, User
from app.domain.value_objects.pagination import Page, PageRequest


class UserRepository(Protocol):
    def get_by_id(self, user_id: uuid.UUID) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def add(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...

    def list(self, page_request: PageRequest) -> Page[User]: ...


class RoleRepository(Protocol):
    def get_by_id(self, role_id: uuid.UUID) -> Role | None: ...

    def get_by_name(self, name: str) -> Role | None: ...

    def list_all(self) -> list[Role]: ...

    def add(self, role: Role) -> Role: ...

    def update(self, role: Role) -> Role: ...


class PermissionRepository(Protocol):
    def get_by_code(self, code: str) -> Permission | None: ...

    def list_all(self) -> list[Permission]: ...

    def add(self, permission: Permission) -> Permission: ...


class PasswordResetTokenRepository(Protocol):
    def add(self, token: PasswordResetToken) -> PasswordResetToken: ...

    def get_by_token_hash(self, token_hash: str) -> PasswordResetToken | None: ...

    def mark_used(self, token_id: uuid.UUID) -> None: ...

    def delete_for_user(self, user_id: uuid.UUID) -> None: ...
