import uuid
from typing import Protocol

from app.domain.entities.rag import NormativaChunk, RagEvaluationRun


class NormativaChunkRepository(Protocol):
    def get_by_chunk_id(self, chunk_id: str) -> NormativaChunk | None: ...

    def upsert(self, chunk: NormativaChunk) -> NormativaChunk: ...

    def list_all(self) -> list[NormativaChunk]: ...

    def count(self) -> int: ...


class RagEvaluationRunRepository(Protocol):
    def add(self, run: RagEvaluationRun) -> RagEvaluationRun: ...

    def get_latest(self) -> RagEvaluationRun | None: ...

    def get_by_id(self, run_id: uuid.UUID) -> RagEvaluationRun | None: ...
